import Sqpack.N21PtsZ.Cov

/-!
# Point-only `s(21) = 5`, kernel-checked with no hypothesis

The certificate is the point-only cover of `point_n21_L5` (wand125/square-packing-bounds), in
its capture-one normalisation `n21-capture-one.txt`: 4,604 point entries of `[0,5]²` with weights
`w/999948000000` of total `20998900000168/999948000000 = 20.99999199975… < 21`, such that every
**closed** unit square inside `[0,5]²` captures weight `≥ 1`.  The zero-margin box tree
`Sqpack/N21PtsZ/*` is generated by Evan Daniel's `lean/scripts/gen_zmtree.py` (untrusted); every
chunk is `decide +kernel` of his `ZMTree.check`, proved sound once (`ZMTree.sound`).  This file is
the same argument as `S13Lower.lean`, with the numbers of this certificate.
-/

namespace SquarePacking

open BoxTree N21PtsZ

/-- **`s(21) ≥ 5`** from the point-only cover: 21 unit squares do not fit in a square of side `< 5`. -/
theorem n21pts_ge_5 : (5 : ℝ) ≤ minSide 21 := by
  have h := le_minSide 1000 4096 5000 4294967296 2147483648 999948000000 pts (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) pts_nodup pts_d4 cov_root 21 5
    (by rw [pts_wsum]; norm_num) (by norm_num)
  norm_num at h ⊢
  exact h

/-- **`s(21) = 5`**, with no hypothesis: with the 5×5 grid (`packs_grid`), `5` is the least side. -/
theorem n21pts_eq_5 : minSide 21 = 5 := by
  have h1 := n21pts_ge_5
  have hp : Packs 21 5 := by
    have h := packs_grid 5 21 (by norm_num)
    simpa using h
  have hb : BddBelow {s | Packs 21 s} := by
    by_contra hnb
    rw [minSide, Real.sInf_of_not_bddBelow hnb] at h1
    norm_num at h1
  exact le_antisymm (csInf_le hb hp) h1

end SquarePacking
